### ISSUE TITLE
채팅창 html, css 구현

### ISSUE THREAD

**Issue by Jude3721** [Doong-Ji/nestalk-frontend#17]
# 채팅창 html, css 작업

- 채팅창 화면 html, css 구성

## 완료 조건 ✅

- [ ] 채팅창 화면 html 구현
- [ ] 채팅창 화면 css 구현

## 관련 이슈 📎

관련 이슈 없음

## 레퍼런스 📚

레퍼런스 없음

**Comment by chloenam** [comment]
issue 전면 수정으로 인해 close 합니다
