### ISSUE TITLE
새로운 채팅 html, css 구현

### ISSUE THREAD

**Issue by EUN-HYE-KIM** [Doong-Ji/nestalk-frontend#25]
# 새로운 채팅 html, css 작업

- 새로운 채팅 html, css 구성

## 완료 조건 ✅

- [ ] 새로운 채팅 html 구현
- [ ] 새로운 채팅 css 구현

## 관련 이슈 📎

관련 이슈 없음

## 레퍼런스 📚

레퍼런스 없음

**Comment by chloenam** [comment]
issue 전면 수정으로 인해 close 합니다

**Comment by chloenam** [comment]
issue 전면 수정으로 인해 close 합니다
