### ISSUE TITLE
퍼블리싱 진행 사항

### ISSUE THREAD

**Issue by Jude3721** [Doong-Ji/nestalk-frontend#7]
# 퍼블리싱 파트 진행 사항

- 각 화면별 캡쳐 진행
- 캡쳐한 화면별 스토리보드 작성

## 완료 조건 ✅

- [x] 모바일웹 화면 캡쳐
- [x] 태블릿PC 화면 캡쳐
- [x] 안드로이드 화면 캡쳐
- [x] 모바일웹 스토리보드 작성
- [x] 태블릿PC 스토리보드 작성
- [ ] 안드로이드 스토리보드 작성

## 관련 이슈 📎

관련 이슈 없음

## 레퍼런스 📚

레퍼런스 없음

**Comment by EUN-HYE-KIM** [comment]
html/css 작업과 함께 구체화
